name: Continuous Delivery for Development

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"
      - docker/*
      - ".github/**"
      - ".gitignore"
      - docker-compose**

jobs:
  cd:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12' ]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag, and push image to Docker Hub
        uses: docker/build-push-action@v6
        id: docker_build
        with:
          file: docker/Dockerfile
          push: true
          build-args: PYTHON_VERSION=${{ matrix.python-version }}
          tags: |
            snow-dugout/skeletons:python-${{ github.sha }}
          labels: |
            python_version=${{ matrix.python-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max