name: Python Interpreter for DEV

on:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/dev.yml"
      - docker/dev.dockerfile
      - requirements.txt

jobs:
  dev:
    name: Build Python Interpreter docker for DEV
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
      - uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout
      - uses: docker/setup-buildx-action@v2
      - name: Login to GitHub registry  # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: docker/dev.dockerfile
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: ghcr.io/${{ github.repository }}:python-${{ matrix.python-version }} # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          cache-from: type=gha
          cache-to: type=gha,mode=max